imports:
    - "@LoevgaardSyliusBarcodePlugin/Resources/config/grids/loevgaard_sylius_barcode_invalid_barcodes.yaml"

framework:
    messenger:
        buses:
            loevgaard_sylius_barcode.command_bus: ~

